# Generated by Django 4.2.1 on 2023-05-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='situación',
            new_name='situacion',
        ),
    ]
