# Generated by Django 4.2.1 on 2023-05-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_rename_situación_vehiculo_situacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='mecanico',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='situacion',
        ),
    ]
