# Generated by Django 4.2.1 on 2023-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_remove_vehiculo_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='MarcaVehiculo',
        ),
    ]
