# Generated by Django 4.2.1 on 2023-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_estado_estadorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
