# Generated by Django 4.2.1 on 2023-06-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_pvp'),
        ('ordenes', '0003_alter_orden_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='monto_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'ProductOrden',
                'verbose_name_plural': 'ProductosOrden',
            },
        ),
    ]
