# Generated by Django 4.2.1 on 2023-06-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_orden_monto_cobrar_productoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoorden',
            name='detalle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productoorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productoorden',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
