# Generated by Django 4.2.1 on 2026-02-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_orden_monto_cobrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('tipo_producto', models.CharField(blank=True, choices=[('inventario', 'Inventario'), ('externo', 'Externo')], max_length=20, null=True)),
                ('pvp', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetallesOrden',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='trabajos_realizados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductoOrden',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden'),
        ),
    ]
