# Generated by Django 4.2.1 on 2026-02-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_detalleorden_orden_kilometraje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='trabajos_realizados',
        ),
    ]
