# Generated by Django 4.2.1 on 2026-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_remove_orden_trabajos_realizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('externo', 'Externo'), ('inventario', 'Inventario')], max_length=20, null=True),
        ),
    ]
